# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

appname: "FlyView"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "template_toolkit"
engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '[%'
    end_tag:   '%]'
  JSON:
    allow_blessed: '1'
    convert_blessed: '1'

error_template: "error"

plugins:
    DBIC:
        usercomments: 
            dsn: "dbi:SQLite:dbname=./data/usercomments.db"
            options:
                sqlite_unicode: 1

list_column_width: 5

update_interval: 600

cache_file: './data/memoize_cache.db'
cache_lifetime: 3600

