# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "registry"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "template_toolkit"
engines:
  template_toolkit:
    encoding:  'utf8'
#     start_tag: '[%'
#     end_tag:   '%]'

session: YAML

mines_file: "data/mines.yml"
secrets_file: "data/secrets.yml"
mine_logs: "data/logged_data.yml"
administrators: "data/admins.yml"
error_log: "data/error_log.yml"

creation_message: "%1$s created: Your token for future updates is '%2$s' - Please remember it: you will not be able to update this registry without passing it back as authToken. Thank you for registering your mine"

update_message: "%s updated successfully - thank you for updating your mine's details"

validation_error_message: "There was an error validating your webservice - you supplied '%1$s'. Please check that this is correct and that your webservice is active and accessible. Please note that the web form requres the home url to include the path, and not just the base url"

forbidden_message: "%1$s exists but was not updated. You do not have sufficient permissions. (either no authentication was supplied, or the authentication supplied does not match what I have on file)."
