log_dir: "/micklem/data/download_logs"
data_dir: "/micklem/data/test"

default_sources:
  - "BioGRID"
  - "EnsemblCompara"
  - "GOAnnotation"
  - "Intact"
  - "IntactVocabulary"
  - "InterPro"
  - "MGIIdentifiers"
  - "NCBIGene"
  - "PubMed"
  - "Reactome"
  - "RGDIdentifiers"
  - "UniProt"


UniProt:
    organisms:
        - 6239
        - 7165
        - 7217
        - 7220
        - 7222
        - 7227
        - 7230
        - 7234
        - 7238
        - 7240
        - 7244
        - 7245
        - 7260
        - 7955
        - 9606
        - 10090
        - 10116
        - 46245
        - 559292
    excluded_organisms:
        - 10091
        - 10092
        - 35531
        - 39442
        - 46244
        - 57486
        - 63221
        - 116058
        - 180454
        - 377270
        - 377271
        - 377586
        - 377587
        - 943925
        - 943926

